version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: peminjaman_ruang_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: peminjaman_ruang
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - peminjaman_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: peminjaman_ruang_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - peminjaman_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  peminjaman_network:
    driver: bridge